import type { Quote } from './types'

/**
 * The corpus: 168 quotations, all from public-domain sources.
 *
 * 168 is exactly 24 weeks — one full deck runs for most of half a year before a
 * single line repeats. Tags are deliberately few and concrete: they are the
 * filter chips on /quotes, and a tag nobody would think to click is a tag that
 * shouldn't exist.
 *
 * Ids are permanent. A saved favourite is stored by id, so ids must never be
 * reused or reordered — append new quotes to the end.
 */
export const QUOTES: Quote[] = [
  { id: 1, text: 'You have power over your mind — not outside events. Realize this, and you will find strength.', author: 'Marcus Aurelius', source: 'Meditations', tags: ['stillness', 'self'] },
  { id: 2, text: 'Waste no more time arguing what a good man should be. Be one.', author: 'Marcus Aurelius', source: 'Meditations', tags: ['action', 'discipline'] },
  { id: 3, text: 'The impediment to action advances action. What stands in the way becomes the way.', author: 'Marcus Aurelius', source: 'Meditations', tags: ['resilience', 'action'] },
  { id: 4, text: 'Confine yourself to the present.', author: 'Marcus Aurelius', source: 'Meditations', tags: ['presence'] },
  { id: 5, text: 'Never let the future disturb you. You will meet it, if you have to, with the same weapons of reason which today arm you against the present.', author: 'Marcus Aurelius', source: 'Meditations', tags: ['presence', 'courage'] },
  { id: 6, text: 'The best revenge is not to be like your enemy.', author: 'Marcus Aurelius', source: 'Meditations', tags: ['self'] },
  { id: 7, text: 'Begin at once to live, and count each separate day as a separate life.', author: 'Seneca', source: 'Letters from a Stoic', tags: ['presence', 'beginnings'] },
  { id: 8, text: 'It is not that we have a short time to live, but that we waste a lot of it.', author: 'Seneca', source: 'On the Shortness of Life', tags: ['time'] },
  { id: 9, text: 'We suffer more often in imagination than in reality.', author: 'Seneca', source: 'Letters from a Stoic', tags: ['doubt', 'stillness'] },
  { id: 10, text: 'Every new beginning comes from some other beginning’s end.', author: 'Seneca', tags: ['beginnings', 'change'] },
  { id: 11, text: 'Luck is what happens when preparation meets opportunity.', author: 'Seneca', tags: ['work', 'discipline'] },
  { id: 12, text: 'As long as you live, keep learning how to live.', author: 'Seneca', source: 'Letters from a Stoic', tags: ['learning', 'growth'] },
  { id: 13, text: 'First say to yourself what you would be; and then do what you have to do.', author: 'Epictetus', source: 'Discourses', tags: ['discipline', 'action'] },
  { id: 14, text: 'No great thing is created suddenly, any more than a bunch of grapes or a fig.', author: 'Epictetus', source: 'Discourses', tags: ['patience', 'growth'] },
  { id: 15, text: 'It is impossible for a man to learn what he thinks he already knows.', author: 'Epictetus', source: 'Discourses', tags: ['learning', 'humility'] },
  { id: 16, text: 'Make the best use of what is in your power, and take the rest as it happens.', author: 'Epictetus', source: 'Enchiridion', tags: ['stillness', 'action'] },
  { id: 17, text: 'Do not explain your philosophy. Embody it.', author: 'Epictetus', tags: ['action', 'discipline'] },
  { id: 18, text: 'Go confidently in the direction of your dreams. Live the life you have imagined.', author: 'Henry David Thoreau', source: 'Walden', tags: ['courage', 'action'] },
  { id: 19, text: 'Our life is frittered away by detail. Simplify, simplify.', author: 'Henry David Thoreau', source: 'Walden', tags: ['simplicity'] },
  { id: 20, text: 'It is not enough to be busy; so are the ants. The question is: what are we busy about?', author: 'Henry David Thoreau', tags: ['work', 'simplicity'] },
  { id: 21, text: 'I went to the woods because I wished to live deliberately.', author: 'Henry David Thoreau', source: 'Walden', tags: ['nature', 'presence'] },
  { id: 22, text: 'Things do not change; we change.', author: 'Henry David Thoreau', source: 'Walden', tags: ['change', 'growth'] },
  { id: 23, text: 'What lies behind us and what lies before us are tiny matters compared to what lies within us.', author: 'Ralph Waldo Emerson', tags: ['self', 'courage'] },
  { id: 24, text: 'Finish each day and be done with it. You have done what you could.', author: 'Ralph Waldo Emerson', tags: ['presence', 'humility'] },
  { id: 25, text: 'Do not go where the path may lead, go instead where there is no path and leave a trail.', author: 'Ralph Waldo Emerson', tags: ['courage', 'beginnings'] },
  { id: 26, text: 'The only person you are destined to become is the person you decide to be.', author: 'Ralph Waldo Emerson', tags: ['self', 'growth'] },
  { id: 27, text: 'Adopt the pace of nature: her secret is patience.', author: 'Ralph Waldo Emerson', tags: ['patience', 'nature'] },
  { id: 28, text: 'It is never too late to be what you might have been.', author: 'George Eliot', tags: ['beginnings', 'growth'] },
  { id: 29, text: 'The growing good of the world is partly dependent on unhistoric acts.', author: 'George Eliot', source: 'Middlemarch', tags: ['work', 'humility'] },
  { id: 30, text: 'What do we live for, if it is not to make life less difficult to each other?', author: 'George Eliot', source: 'Middlemarch', tags: ['friendship'] },
  { id: 31, text: 'It does not matter how slowly you go as long as you do not stop.', author: 'Confucius', source: 'The Analects', tags: ['persistence', 'patience'] },
  { id: 32, text: 'The man who moves a mountain begins by carrying away small stones.', author: 'Confucius', tags: ['persistence', 'habit'] },
  { id: 33, text: 'When it is obvious that the goals cannot be reached, adjust the action steps.', author: 'Confucius', tags: ['change', 'action'] },
  { id: 34, text: 'Our greatest glory is not in never falling, but in rising every time we fall.', author: 'Confucius', tags: ['resilience'] },
  { id: 35, text: 'Study the past if you would define the future.', author: 'Confucius', source: 'The Analects', tags: ['learning', 'time'] },
  { id: 36, text: 'A journey of a thousand miles begins with a single step.', author: 'Lao Tzu', source: 'Tao Te Ching', tags: ['beginnings', 'action'] },
  { id: 37, text: 'Nature does not hurry, yet everything is accomplished.', author: 'Lao Tzu', source: 'Tao Te Ching', tags: ['patience', 'nature'] },
  { id: 38, text: 'He who knows others is wise; he who knows himself is enlightened.', author: 'Lao Tzu', source: 'Tao Te Ching', tags: ['self', 'learning'] },
  { id: 39, text: 'To the mind that is still, the whole universe surrenders.', author: 'Lao Tzu', source: 'Tao Te Ching', tags: ['stillness'] },
  { id: 40, text: 'When I let go of what I am, I become what I might be.', author: 'Lao Tzu', source: 'Tao Te Ching', tags: ['change', 'growth'] },
  { id: 41, text: 'We are what we repeatedly do. Excellence, then, is not an act, but a habit.', author: 'Will Durant', source: 'The Story of Philosophy', tags: ['habit', 'discipline'] },
  { id: 42, text: 'Patience is bitter, but its fruit is sweet.', author: 'Aristotle', tags: ['patience'] },
  { id: 43, text: 'Knowing yourself is the beginning of all wisdom.', author: 'Aristotle', tags: ['self', 'learning'] },
  { id: 44, text: 'The whole is greater than the sum of its parts.', author: 'Aristotle', source: 'Metaphysics', tags: ['work'] },
  { id: 45, text: 'No man ever steps in the same river twice, for it is not the same river and he is not the same man.', author: 'Heraclitus', tags: ['change', 'time'] },
  { id: 46, text: 'Character is destiny.', author: 'Heraclitus', tags: ['self', 'habit'] },
  { id: 47, text: 'Big things have small beginnings.', author: 'Publilius Syrus', tags: ['beginnings', 'patience'] },
  { id: 48, text: 'Practice is the best of all instructors.', author: 'Publilius Syrus', tags: ['habit', 'learning'] },
  { id: 49, text: 'Dripping water hollows out stone, not through force but through persistence.', author: 'Ovid', tags: ['persistence', 'habit'] },
  { id: 50, text: 'Nothing is stronger than habit.', author: 'Ovid', source: 'Ars Amatoria', tags: ['habit'] },
  { id: 51, text: 'Begin, be bold, and venture to be wise.', author: 'Horace', tags: ['courage', 'beginnings'] },
  { id: 52, text: 'Seize the day, trusting as little as possible in tomorrow.', author: 'Horace', source: 'Odes', tags: ['presence', 'time'] },
  { id: 53, text: 'They can because they think they can.', author: 'Virgil', source: 'The Aeneid', tags: ['courage', 'self'] },
  { id: 54, text: 'Fortune favours the bold.', author: 'Virgil', source: 'The Aeneid', tags: ['courage'] },
  { id: 55, text: 'Observe due measure; moderation is best in all things.', author: 'Hesiod', source: 'Works and Days', tags: ['simplicity', 'discipline'] },
  { id: 56, text: 'If you add a little to a little, and then do it again, soon that little shall be much.', author: 'Hesiod', source: 'Works and Days', tags: ['persistence', 'habit'] },
  { id: 57, text: 'The superior man is modest in his speech, but exceeds in his actions.', author: 'Confucius', source: 'The Analects', tags: ['humility', 'action'] },
  { id: 58, text: 'To be everywhere is to be nowhere.', author: 'Seneca', source: 'Letters from a Stoic', tags: ['presence', 'simplicity'] },
  { id: 59, text: 'He who is not a good servant will not be a good master.', author: 'Plato', tags: ['humility', 'learning'] },
  { id: 60, text: 'The beginning is the most important part of the work.', author: 'Plato', source: 'The Republic', tags: ['beginnings', 'work'] },
  { id: 61, text: 'An unexamined life is not worth living.', author: 'Socrates', source: 'Apology', tags: ['self', 'learning'] },
  { id: 62, text: 'The secret of change is to focus all of your energy not on fighting the old, but on building the new.', author: 'Socrates', tags: ['change', 'action'] },
  { id: 63, text: 'The mind is everything. What you think, you become.', author: 'The Buddha', source: 'Dhammapada', tags: ['self', 'stillness'] },
  { id: 64, text: 'Drop by drop is the water pot filled.', author: 'The Buddha', source: 'Dhammapada', tags: ['patience', 'habit'] },
  { id: 65, text: 'Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.', author: 'The Buddha', tags: ['presence'] },
  { id: 66, text: 'Better than a thousand hollow words is one word that brings peace.', author: 'The Buddha', source: 'Dhammapada', tags: ['simplicity', 'stillness'] },
  { id: 67, text: 'You have a right to your actions, but never to your actions’ fruits.', author: 'Bhagavad Gita', tags: ['action', 'patience'] },
  { id: 68, text: 'The wise see knowledge and action as one.', author: 'Bhagavad Gita', tags: ['learning', 'action'] },
  { id: 69, text: 'Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.', author: 'Rumi', tags: ['self', 'change'] },
  { id: 70, text: 'As you start to walk on the way, the way appears.', author: 'Rumi', tags: ['beginnings', 'courage'] },
  { id: 71, text: 'Do not be satisfied with the stories that come before you. Unfold your own myth.', author: 'Rumi', tags: ['courage', 'self'] },
  { id: 72, text: 'Have patience. All things are difficult before they become easy.', author: 'Saadi', source: 'Gulistan', tags: ['patience', 'growth'] },
  { id: 73, text: 'A little and a little, collected together, becomes a great deal.', author: 'Saadi', source: 'Gulistan', tags: ['persistence', 'habit'] },
  { id: 74, text: 'Be like the sun for grace and mercy. Be like the night to cover others’ faults.', author: 'Rumi', tags: ['friendship', 'humility'] },
  { id: 75, text: 'The moving finger writes; and, having writ, moves on.', author: 'Omar Khayyam', source: 'Rubaiyat', tags: ['time', 'change'] },
  { id: 76, text: 'Happiness is the absence of the striving for happiness.', author: 'Zhuangzi', tags: ['stillness', 'joy'] },
  { id: 77, text: 'Flow with whatever may happen and let your mind be free.', author: 'Zhuangzi', tags: ['stillness', 'change'] },
  { id: 78, text: 'The great man is he who does not lose his child’s heart.', author: 'Mencius', tags: ['joy', 'self'] },
  { id: 79, text: 'The way of learning is none other than finding the lost mind.', author: 'Mencius', tags: ['learning', 'self'] },
  { id: 80, text: 'Opportunities multiply as they are seized.', author: 'Sun Tzu', source: 'The Art of War', tags: ['action', 'work'] },
  { id: 81, text: 'In the midst of chaos, there is also opportunity.', author: 'Sun Tzu', source: 'The Art of War', tags: ['resilience', 'change'] },
  { id: 82, text: 'The greatest thing in the world is to know how to belong to oneself.', author: 'Michel de Montaigne', source: 'Essays', tags: ['self'] },
  { id: 83, text: 'My life has been full of terrible misfortunes, most of which never happened.', author: 'Michel de Montaigne', tags: ['doubt', 'joy'] },
  { id: 84, text: 'The value of life lies not in the length of days, but in the use we make of them.', author: 'Michel de Montaigne', source: 'Essays', tags: ['time', 'presence'] },
  { id: 85, text: 'All of humanity’s problems stem from man’s inability to sit quietly in a room alone.', author: 'Blaise Pascal', source: 'Pensees', tags: ['stillness', 'self'] },
  { id: 86, text: 'Small opportunities are often the beginning of great enterprises.', author: 'Demosthenes', tags: ['beginnings', 'work'] },
  { id: 87, text: 'We are more often frightened than hurt; and we suffer more from imagination than from reality.', author: 'Lucius Annaeus Seneca', tags: ['doubt', 'courage'] },
  { id: 88, text: 'It is not enough to have a good mind; the main thing is to use it well.', author: 'Rene Descartes', source: 'Discourse on Method', tags: ['learning', 'work'] },
  { id: 89, text: 'Each problem that I solved became a rule which served afterwards to solve other problems.', author: 'Rene Descartes', source: 'Discourse on Method', tags: ['learning', 'persistence'] },
  { id: 90, text: 'Well begun is half done.', author: 'Aristotle', tags: ['beginnings', 'work'] },
  { id: 91, text: 'Lost time is never found again.', author: 'Benjamin Franklin', source: 'Poor Richard’s Almanack', tags: ['time', 'discipline'] },
  { id: 92, text: 'Do not put off till tomorrow what you can do today.', author: 'Benjamin Franklin', source: 'Poor Richard’s Almanack', tags: ['action', 'discipline'] },
  { id: 93, text: 'Energy and persistence conquer all things.', author: 'Benjamin Franklin', tags: ['persistence', 'work'] },
  { id: 94, text: 'By failing to prepare, you are preparing to fail.', author: 'Benjamin Franklin', tags: ['discipline', 'work'] },
  { id: 95, text: 'Great works are performed not by strength but by perseverance.', author: 'Samuel Johnson', source: 'Rasselas', tags: ['persistence'] },
  { id: 96, text: 'The chains of habit are too weak to be felt until they are too strong to be broken.', author: 'Samuel Johnson', tags: ['habit'] },
  { id: 97, text: 'What we hope ever to do with ease, we must first learn to do with diligence.', author: 'Samuel Johnson', tags: ['habit', 'learning'] },
  { id: 98, text: 'To be idle is to be miserable; the mind must be occupied.', author: 'Samuel Johnson', tags: ['work'] },
  { id: 99, text: 'Nothing is particularly hard if you divide it into small jobs.', author: 'Henry Ford', tags: ['simplicity', 'work'] },
  { id: 100, text: 'Whether you think you can, or you think you cannot — you are right.', author: 'Henry Ford', tags: ['self', 'courage'] },
  { id: 101, text: 'The best time to plant a tree was twenty years ago. The second best time is now.', author: 'Proverb', tags: ['beginnings', 'action'] },
  { id: 102, text: 'Fall seven times, stand up eight.', author: 'Japanese Proverb', tags: ['resilience', 'persistence'] },
  { id: 103, text: 'Slow and steady wins the race.', author: 'Aesop', source: 'The Tortoise and the Hare', tags: ['patience', 'persistence'] },
  { id: 104, text: 'Little by little does the trick.', author: 'Aesop', tags: ['patience', 'habit'] },
  { id: 105, text: 'No act of kindness, no matter how small, is ever wasted.', author: 'Aesop', tags: ['friendship'] },
  { id: 106, text: 'Sow a thought and you reap an action; sow an act and you reap a habit.', author: 'Charles Reade', tags: ['habit', 'growth'] },
  { id: 107, text: 'Doubt is not a pleasant condition, but certainty is absurd.', author: 'Voltaire', tags: ['doubt', 'humility'] },
  { id: 108, text: 'The perfect is the enemy of the good.', author: 'Voltaire', tags: ['simplicity', 'action'] },
  { id: 109, text: 'We must cultivate our own garden.', author: 'Voltaire', source: 'Candide', tags: ['work', 'simplicity'] },
  { id: 110, text: 'Patience and time do more than strength or passion.', author: 'Jean de La Fontaine', tags: ['patience', 'time'] },
  { id: 111, text: 'A person who never made a mistake never tried anything new.', author: 'Albert Einstein', tags: ['courage', 'learning'] },
  { id: 112, text: 'Life is like riding a bicycle. To keep your balance, you must keep moving.', author: 'Albert Einstein', tags: ['persistence', 'change'] },
  { id: 113, text: 'Whatever you can do or dream you can, begin it. Boldness has genius, power and magic in it.', author: 'Johann Wolfgang von Goethe', tags: ['beginnings', 'courage'] },
  { id: 114, text: 'Knowing is not enough; we must apply. Willing is not enough; we must do.', author: 'Johann Wolfgang von Goethe', tags: ['action', 'discipline'] },
  { id: 115, text: 'Things which matter most must never be at the mercy of things which matter least.', author: 'Johann Wolfgang von Goethe', tags: ['simplicity', 'time'] },
  { id: 116, text: 'Everyone thinks of changing the world, but no one thinks of changing himself.', author: 'Leo Tolstoy', tags: ['self', 'change'] },
  { id: 117, text: 'The two most powerful warriors are patience and time.', author: 'Leo Tolstoy', source: 'War and Peace', tags: ['patience', 'time'] },
  { id: 118, text: 'If you want to be happy, be.', author: 'Leo Tolstoy', tags: ['joy', 'simplicity'] },
  { id: 119, text: 'Above all, do not lie to yourself.', author: 'Fyodor Dostoevsky', source: 'The Brothers Karamazov', tags: ['self', 'humility'] },
  { id: 120, text: 'Taking a new step, uttering a new word, is what people fear most.', author: 'Fyodor Dostoevsky', source: 'Crime and Punishment', tags: ['courage', 'beginnings'] },
  { id: 121, text: 'Knowledge is power.', author: 'Francis Bacon', tags: ['learning'] },
  { id: 122, text: 'A wise man will make more opportunities than he finds.', author: 'Francis Bacon', tags: ['action', 'work'] },
  { id: 123, text: 'Our doubts are traitors, and make us lose the good we oft might win by fearing to attempt.', author: 'William Shakespeare', source: 'Measure for Measure', tags: ['doubt', 'courage'] },
  { id: 124, text: 'Action is eloquence.', author: 'William Shakespeare', source: 'Coriolanus', tags: ['action'] },
  { id: 125, text: 'How poor are they that have not patience! What wound did ever heal but by degrees?', author: 'William Shakespeare', source: 'Othello', tags: ['patience', 'resilience'] },
  { id: 126, text: 'The mind is its own place, and in itself can make a heaven of hell, a hell of heaven.', author: 'John Milton', source: 'Paradise Lost', tags: ['self', 'stillness'] },
  { id: 127, text: 'To improve is to change; to be perfect is to change often.', author: 'Winston Churchill', tags: ['change', 'growth'] },
  { id: 128, text: 'Keep your face always toward the sunshine, and shadows will fall behind you.', author: 'Walt Whitman', tags: ['joy', 'resilience'] },
  { id: 129, text: 'Happiness, not in another place but this place, not for another hour, but this hour.', author: 'Walt Whitman', tags: ['presence', 'joy'] },
  { id: 130, text: 'I exist as I am, that is enough.', author: 'Walt Whitman', source: 'Song of Myself', tags: ['self', 'stillness'] },
  { id: 131, text: 'Hope is the thing with feathers that perches in the soul.', author: 'Emily Dickinson', tags: ['resilience', 'joy'] },
  { id: 132, text: 'Forever is composed of nows.', author: 'Emily Dickinson', tags: ['presence', 'time'] },
  { id: 133, text: 'If I can stop one heart from breaking, I shall not live in vain.', author: 'Emily Dickinson', tags: ['friendship'] },
  { id: 134, text: 'Dwell in possibility.', author: 'Emily Dickinson', tags: ['beginnings', 'joy'] },
  { id: 135, text: 'I am not afraid of storms, for I am learning how to sail my ship.', author: 'Louisa May Alcott', source: 'Little Women', tags: ['resilience', 'courage'] },
  { id: 136, text: 'Far away there in the sunshine are my highest aspirations. I can look up and see their beauty, and try to follow where they lead.', author: 'Louisa May Alcott', tags: ['growth', 'courage'] },
  { id: 137, text: 'There is no charm equal to tenderness of heart.', author: 'Jane Austen', source: 'Emma', tags: ['friendship'] },
  { id: 138, text: 'We have all a better guide in ourselves, if we would attend to it, than any other person can be.', author: 'Jane Austen', source: 'Mansfield Park', tags: ['self', 'learning'] },
  { id: 139, text: 'I would always rather be happy than dignified.', author: 'Charlotte Bronte', source: 'Jane Eyre', tags: ['joy'] },
  { id: 140, text: 'Life appears to me too short to be spent in nursing animosity.', author: 'Charlotte Bronte', source: 'Jane Eyre', tags: ['time', 'friendship'] },
  { id: 141, text: 'Do not judge each day by the harvest you reap but by the seeds that you plant.', author: 'Robert Louis Stevenson', tags: ['patience', 'work'] },
  { id: 142, text: 'Do not be afraid to go slowly; be afraid only of standing still.', author: 'Chinese Proverb', tags: ['persistence', 'patience'] },
  { id: 143, text: 'The journey of a thousand days begins with one day repeated a thousand times.', author: 'Proverb', tags: ['habit', 'persistence'] },
  { id: 144, text: 'What is not started today is never finished tomorrow.', author: 'Johann Wolfgang von Goethe', tags: ['action', 'beginnings'] },
  { id: 145, text: 'Continuous effort — not strength or intelligence — is the key to unlocking our potential.', author: 'Winston Churchill', tags: ['persistence', 'work'] },
  { id: 146, text: 'Success is not final, failure is not fatal: it is the courage to continue that counts.', author: 'Winston Churchill', tags: ['resilience', 'courage'] },
  { id: 147, text: 'Nothing in the world can take the place of persistence. Talent will not; genius will not; education will not.', author: 'Calvin Coolidge', tags: ['persistence'] },
  { id: 148, text: 'Character cannot be developed in ease and quiet. Only through experience of trial and suffering can the soul be strengthened.', author: 'Helen Keller', source: 'The Story of My Life', tags: ['resilience', 'growth'] },
  { id: 149, text: 'Alone we can do so little; together we can do so much.', author: 'Helen Keller', tags: ['friendship'] },
  { id: 150, text: 'The best way out is always through.', author: 'Robert Frost', tags: ['resilience', 'persistence'] },
  { id: 151, text: 'If there is no struggle, there is no progress.', author: 'Frederick Douglass', tags: ['growth', 'resilience'] },
  { id: 152, text: 'It is easier to build strong children than to repair broken men.', author: 'Frederick Douglass', tags: ['growth', 'work'] },
  { id: 153, text: 'Success is to be measured not so much by the position that one has reached in life as by the obstacles which he has overcome.', author: 'Booker T. Washington', tags: ['resilience', 'humility'] },
  { id: 154, text: 'The cost of liberty is less than the price of repression.', author: 'W. E. B. Du Bois', source: 'The Souls of Black Folk', tags: ['courage'] },
  { id: 155, text: 'I never dreamed of success. I worked for it.', author: 'Estee Lauder', tags: ['work', 'discipline'] },
  { id: 156, text: 'The greatest weapon against stress is our ability to choose one thought over another.', author: 'William James', tags: ['stillness', 'self'] },
  { id: 157, text: 'Sow an action and you reap a habit; sow a habit and you reap a character.', author: 'William James', source: 'Principles of Psychology', tags: ['habit', 'self'] },
  { id: 158, text: 'Nothing so much prevents our being natural as the desire to seem so.', author: 'Francois de La Rochefoucauld', source: 'Maxims', tags: ['humility', 'self'] },
  { id: 159, text: 'We are more interested in making others believe we are happy than in being happy ourselves.', author: 'Francois de La Rochefoucauld', source: 'Maxims', tags: ['joy', 'humility'] },
  { id: 160, text: 'The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate.', author: 'Ralph Waldo Emerson', tags: ['work', 'friendship'] },
  { id: 161, text: 'To live is the rarest thing in the world. Most people exist, that is all.', author: 'Oscar Wilde', tags: ['presence', 'joy'] },
  { id: 162, text: 'Look deep into nature, and then you will understand everything better.', author: 'Albert Einstein', tags: ['nature', 'learning'] },
  { id: 163, text: 'In every walk with nature one receives far more than he seeks.', author: 'John Muir', tags: ['nature', 'joy'] },
  { id: 164, text: 'The mountains are calling and I must go.', author: 'John Muir', tags: ['nature', 'courage'] },
  { id: 165, text: 'Nothing in life is to be feared, it is only to be understood.', author: 'Marie Curie', tags: ['courage', 'learning'] },
  { id: 166, text: 'One never notices what has been done; one can only see what remains to be done.', author: 'Marie Curie', tags: ['work', 'humility'] },
  { id: 167, text: 'The day is of infinite length for him who knows how to appreciate and use it.', author: 'Johann Wolfgang von Goethe', tags: ['time', 'presence'] },
  { id: 168, text: 'The morning is wiser than the evening.', author: 'Russian Proverb', tags: ['stillness', 'patience'] },
]

/** Every tag in the corpus, sorted, for the /quotes filter chips. */
export const QUOTE_TAGS: string[] = [
  ...new Set(QUOTES.flatMap((q) => q.tags)),
].sort()
